### PR TITLE
Analysis Pre-Work

### PR DESCRIPTION
**Pull request by georgiosd**
Draft but lots there so prob a good idea to start reviewing it :)

fixes ENGIN-565

### CODE REVIEW

**Review by garrettmaring — APPROVED** [review]
lgsf!

**Comment by georgiosd** [comment]
@garrettmaring this is good to merge if you want it deployed ASAP.

**Comment by georgiosd** [comment]
Apologies in advance for including multiple tickets in this PR - some of the latter work depends on the changes so given timezone constraints I thought it best to break the rule than create more work.

**Comment by georgiosd** [comment]
Merged approved work/fixes to main, left analysis feature to this PR and waiting for direction on submissions.

**Pull request closed without merging**
